AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  VPC:
    Description: VPC CIDR Ip for SG
    Type: AWS::EC2::VPC::Id
  ProjectName:
    Description: Projectname Ip for SG
    Type: String
    Default: ECSdemo
         
Resources:
#security group
  ELBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ELB Security Group
      GroupName: !Sub ${ProjectName}-ALB
      VpcId:
         Ref: VPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 8080
        ToPort: 8080
        CidrIp: 0.0.0.0/0

  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Public subnet sercurity 
      GroupName: !Sub ${ProjectName}-ECS
      VpcId:
         Ref: VPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0

   
