AWSTemplateFormatVersion: "2010-09-09"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Project Name Prefix
        Parameters:
          - ProjectName
      - Label:
          default: InternetALB Configuration
        Parameters:
          - InternetALBName
          - TargetGroupName
    ParameterLabels:
      InternetALBName:
        default: InternetALBName
      TargetGroupName:
        default: TargetGroupName

Parameters:
  VpcId:
    Description: Specify VPC Id for ALB
    Type: AWS::EC2::VPC::Id
  ALBSubnetId1:
    Description: Specify Subnet1 Id for ALB
    Type: AWS::EC2::Subnet::Id
  ALBSubnetId2:
    Description: Specify Subnet2 Id for ALB
    Type: AWS::EC2::Subnet::Id
  ALBSecurityGroupId:
    Description: Specify SG for ALB
    Type: AWS::EC2::SecurityGroup::Id
  #ProjectName
  ProjectName:
    Default: ECSdemo
    Type: String
  #InternetALBName
  InternetALBName:
    Default: ECSALBdemo
    Type: String
  TargetGroupName:
    Default: ECStargetgroupdemo
    Type: String   


Resources:
# ------------------------------------------------------------#
#  Target Group
# ------------------------------------------------------------#
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Name: !Sub ${ProjectName}-${TargetGroupName}
      Protocol: HTTP
      Port: 80
      TargetType: ip

# ------------------------------------------------------------#
#  Internet Aplication Load Balancer
# ------------------------------------------------------------#
  InternetALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${ProjectName}-${InternetALBName}
      HealthCheckIntervalSeconds: 30
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 15
      HealthyThresholdCount: 5
      Matcher:
        HttpCode: '200'
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${InternetALBName}
      Scheme: internet-facing
      LoadBalancerAttributes:
        - Key: deletion_protection.enabled
          Value: false
        - Key: idle_timeout.timeout_seconds
          Value: 60
        - Key: access_logs.s3.enabled
          Value: true
        - Key: "access_logs.s3.bucket"
          Value: !Sub alb-log-${AWS::AccountId}
      SecurityGroups:
        - !Ref ALBSecurityGroupId
      Subnets:
        - !Ref ALBSubnetId1
        - !Ref ALBSubnetId2

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      LoadBalancerArn: !Ref InternetALB
      Port: 80
      Protocol: HTTP
      Port: 8080
      Protocol: HTTP
